services:
  testdb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=sgga_test'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'
    ports:
      - '3306:3306'
    volumes:
      - testdb:/data/db

volumes:
  testdb: